server:
  port: 8090
  servlet:
    context-path: /api

spring:
  main:
    banner-mode: off
  jmx:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/sbdemo